export default {
  // wallet slider
  CHANGE_ACTIVE_SLIDE: "CHANGE_ACTIVE_SLIDE",

  // profile
  CHANGE_PROFILE: "CHANGE_PROFILE",

  // server
  CHECK_NETWORK_START: "CHECK_NETWORK_LOADING_START",
  CHECK_NETWORK_SUCCESS: "CHECK_NETWORK_SUCCESS",
  CHECK_NETWORK_ERROR: "CHECK_NETWORK_ERROR",
  CHECK_NETWORK_FINISH: "CHECK_NETWORK_FINISH",
  CHANGE_NETWORK_CONFIG: "CHANGE_NETWORK_CONFIG",

  // auth
  SECURE_CHECKING_START: "SECURE_CHECKING_START",
  SECURE_CHECKING_FINISH: "SECURE_CHECKING_FINISH",
  CHANGE_IS_LOCAL_AUTHENTICATED: "CHANGE_IS_LOCAL_AUTHENTICATED",
  CHANGE_IS_PASSCODE_EXIST: "CHANGE_IS_PASSCODE_EXIST",
  CHANGE_BIOMETRIC_IS_ON: "CHANGE_BIOMETRIC_IS_ON",
  CHANGE_BIOMETRIC_METHOD: "CHANGE_BIOMETRIC_METHOD",
  CHANGE_AUTO_LOCK_VALUE: "CHANGE_AUTO_LOCK_VALUE",
  CHANGE_APP_LOCKED_TIME: "CHANGE_APP_LOCKED_TIME",
};
