export default {
  WALLET_LOAD_START: "WALLET_LOAD_START",
  WALLET_LIST_LOAD_START: "WALLET_LIST_LOAD_START",
  WALLET_LIST_LOAD_SUCCESS: "WALLET_LIST_LOAD_SUCCESS",
  WALLET_LIST_LOAD_ERROR: "WALLET_LIST_LOAD_ERROR",
  WALLET_LIST_LOAD_FINISH: "WALLET_LIST_LOAD_FINISH",
  WALLET_LOAD_ERROR: "WALLET_LOAD_ERROR",
  WALLET_LOAD_SUCCESS: "WALLET_LOAD_SUCCESS",
  WALLET_LOAD_FINISH: "WALLET_LOAD_FINISH",

  CHANGE_AMOUNT_VALUE: "CHANGE_AMOUNT_VALUE",
  CHANGE_RECEIVE_ADDRESS: "CHANGE_RECEIVE_ADDRESS",
  RESET_SEND_VALUES: "RESET_SEND_VALUES",
};
